name: deploy

on:
  push:
    branches:
      - develop
      - main
      - homolog
      - 'feature/*'
      - 'feat/*'
      - 'fix/*'
      - 'hotfix/*'
  pull_request:
    branches:
      - develop
      - main
      - homolog

jobs: 
  check-branch:
    name: Check Branch
    runs-on: ubuntu-latest
    outputs:
      run-quality: ${{ steps.set-run-quality.outputs.run-quality }}
    steps:
      - name: Set Run Quality
        id: set-run-quality
        run: echo "run-quality=${{ github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/homoloh' || github.ref == 'refs/heads/main' }}" 

  install-dev:
    name: prepare-dev
    runs-on: ubuntu-latest
    needs: check-branch
    if: needs.check-branch.outputs.run-quality == 'true'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-dev-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install


  install-hml:
    name: prepare-hml
    runs-on: ubuntu-latest
    needs: check-branch
    if: needs.check-branch.outputs.run-quality == 'true' && github.ref == 'refs/heads/homolog'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-hml-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install


  install-prod:
    name: prepare-prod
    runs-on: ubuntu-latest
    needs: check-branch
    if: needs.check-branch.outputs.run-quality == 'true' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-prd-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install

  quality:
    name: quality
    runs-on: ubuntu-latest
    needs: [install-dev, install-hml, install-prod]
    strategy:
      matrix:
        environment: [dev, hml, prd]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ matrix.environment }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Run ts-prune 
        run: yarn ts-prune --error
