name: deploy-dev
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
      - feature/*
      - feat/*
      - fix/*
      - hotfix/*

jobs: 
  install:
    name: prepare
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install

  unusedexports:
    name: quality
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Run ts-prune 
        run: yarn ts-prune --error

name: deploy-hml
on:
  push:
    branches:
      - homolog
  pull_request:
    branches:
      - homolog

jobs: 
  install:
    name: prepare
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install

  unusedexports:
    name: quality
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Run ts-prune 
        run: yarn ts-prune --error

name: deploy-prd
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  install:
    name: prepare
    environment:
      name: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Install dependencies
        run: yarn install

  unusedexports:
    name: quality
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
        
      - name: Run ts-prune 
        run: yarn ts-prune --error