name: deploy

on:
  push:
    branches:
      - develop
      - main
      - homolog
      - 'feature/*'
      - 'feat/*'
      - 'fix/*'
      - 'hotfix/*'

jobs:
  install:
    name: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}"

      - name: Install dependencies
        run: yarn install

  lint:
    name: lint
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}"

      - name: Run lint
        run: yarn lint

  tests:
    name: tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}"

      - name: Run tests
        run: echo "tests is running..."

  quality:
    name: quality
    runs-on: ubuntu-latest
    needs: [tests]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}"

      - name: Run ts-prune
        run: yarn ts-prune --error

  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: "${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}"

      - name: Run tests
        run: echo "deploy is running..."
